# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Final Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final Project

    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'

  target 'Final ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Final ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
